name: hedgewars
version: 0.9.25
summary: A turn based strategy, artillery, action and comedy game
description: |
  Hedgewars is a turn based strategy, artillery, action and comedy game, featuring the antics of pink hedgehogs with attitude as they battle from the depths of hell to the depths of space.

  As commander, it's your job to assemble your crack team of hedgehog soldiers and bring the war to your enemy.
  
  Game features:
    - Hilarious and strategic turn based combat for up to 8 players
    - Both local and network multiplayer, with optional AI opponents
    - Two singleplayer campaigns with a total of 24 missions
    - Utilize 57 (and counting) devastating weapons and utilities! Defeat your foes with simple weapons like grenades or take it to the next level and trash entire landscapes with weapons like the watermelon bomb or piano strike
    - Improve your skills in a total of more than 25 single missions for learning the game, target practice, challenges and just for fun
    - Battle on an infinite number of randomly generated maps with 37 environments, or choose from 44 set image maps, or even draw your own in an editor
    - Play the game your with 25 different game modifiers, tweak almost every aspect of the match
    - Save your favourite gameplay settings in schemes
    - Customize your team, with over 280 hats/costumes, 32 graves, 13 forts, 100s of flags and 13 unique voice packs
    - Huge battles with up to 48 hedgehogs
    - Play both singleplayer and multiplayer mini games
    - If that's not enough, you can download tons of community content packs straight through the game or even plugin your own custom graves, maps, hats and costumes, and a lot of other artwork. See the HWKB to learn more

confinement: strict
base: core18
#icon: resources/images/icon512.png

apps:
  hedgewars:
    environment:
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
    command: desktop-launch hedgewars -platform xcb
    plugs: [ x11, wayland, desktop, desktop-legacy, opengl, alsa, pulseaudio, network, network-bind ]

parts:
  hedgewars:
    source-type: hg
    source: https://hg.hedgewars.org/hedgewars/
    source-tag: 0.9.25-release
    plugin: cmake
    configflags: [ "-DNOSERVER=0" ]
    build-packages:
        - g++
        - qtbase5-dev
        - qtbase5-private-dev
        - qttools5-dev-tools
        - qttools5-dev
        - qt5-style-plugins
        - libsdl-ttf2.0-dev
        - libsdl2-dev
        - libsdl2-net-dev
        - libsdl2-mixer-dev
        - libsdl2-image-dev
        - libsdl2-ttf-dev
        - liblua5.1-dev
        - fpc
        - libphysfs-dev
        - fonts-dejavu-core
        - ttf-wqy-zenhei
        - libpng-dev
        - libavcodec-dev
        - libavformat-dev
        - freeglut3-dev
        - ghc
        - libghc-binary-dev
        - libghc-bytestring-show-dev
        - libghc-sandi-dev
        - libghc-deepseq-dev
        - libghc-hslogger-dev
        - libghc-mtl-dev
        - libghc-network-dev
        - libghc-parsec3-dev
        - libghc-utf8-string-dev
        - libghc-vector-dev
        - libghc-random-dev
        - libghc-zlib-dev
        - libghc-sha-dev
        - libghc-entropy-dev
        - libghc-regex-tdfa-dev
        - libghc-aeson-dev
        - libghc-yaml-dev
        - libghc-text-dev
    stage-packages:
        - fonts-dejavu-core
        - fonts-wqy-zenhei
        - freeglut3
        - libatomic1
        - libavcodec-extra57
        - libavformat57
        - libavutil55
        - libffi6
        - libgcc1
        - libglew2.0
        - libgmp10
        - liblua5.1-0
        - libphysfs1
        - libpng16-16
        - libqt5core5a
        - libqt5gui5
        - libqt5network5
        - libqt5widgets5
        - libsdl-ttf2.0-0
        - libsdl2-2.0-0
        - libsdl2-image-2.0-0
        - libsdl2-mixer-2.0-0
        - libsdl2-net-2.0-0
        - libsdl2-ttf-2.0-0
        - libstdc++6
        - qt5-style-plugins
        - ttf-dejavu-core
        - zlib1g
    after: [ desktop-qt5 ]
  desktop-qt5:
    build-packages:
        - qtbase5-dev
        - dpkg-dev
    make-parameters:
        - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libqt5svg5
        - locales-all
        - xdg-user-dirs

